spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VoucherManagementApplication # ${datasource.url}
    username: root # ${datasource.username}
    password: 1234 # ${datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    hidden-method:
      filter:
        enabled: true