# FileBlackListProperties 라는 class getFileName, getFilePath
# FileVoucherProperties 라는 class getFileName, getFilePath

file:
  customer-black-list:
    name: customer_blacklist.csv
    path: resources/

  voucher-list:
    name: voucherList.txt
    path: resources/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VoucherManagementApplication
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

